// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateAccount = `-- name: ActivateAccount :exec
UPDATE accounts
SET
    status = 'ACTIVE'
WHERE
    id = $1
`

func (q *Queries) ActivateAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, activateAccount, id)
	return err
}

const addBalance = `-- name: AddBalance :exec
UPDATE accounts
SET
    balance = balance + $1
WHERE
    id = $2
`

type AddBalanceParams struct {
	Balance int64       `json:"balance"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) AddBalance(ctx context.Context, arg AddBalanceParams) error {
	_, err := q.db.Exec(ctx, addBalance, arg.Balance, arg.ID)
	return err
}

const checkIfAccountNumberExists = `-- name: CheckIfAccountNumberExists :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            accounts
        WHERE
            account_number = $1
    )
`

func (q *Queries) CheckIfAccountNumberExists(ctx context.Context, accountNumber string) (bool, error) {
	row := q.db.QueryRow(ctx, checkIfAccountNumberExists, accountNumber)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUserAccount = `-- name: CreateUserAccount :one
INSERT INTO
    accounts (account_number, user_id, currency)
VALUES
    ($1, $2, $3)
RETURNING
    id, user_id, account_number, currency, balance, status, created_at, updated_at
`

type CreateUserAccountParams struct {
	AccountNumber string      `json:"account_number"`
	UserID        pgtype.UUID `json:"user_id"`
	Currency      string      `json:"currency"`
}

// db/queries/accounts.sql
func (q *Queries) CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createUserAccount, arg.AccountNumber, arg.UserID, arg.Currency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountNumber,
		&i.Currency,
		&i.Balance,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT
    id, user_id, account_number, currency, balance, status, created_at, updated_at
FROM
    accounts
WHERE
    id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountNumber,
		&i.Currency,
		&i.Balance,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByAccountNumber = `-- name: GetAccountByAccountNumber :one
SELECT
    accounts.id, user_id, account_number, currency, balance, status, accounts.created_at, accounts.updated_at, users.id, email, password_hash, full_name, is_verified, refresh_token, verification_token, users.created_at, users.updated_at
FROM
    accounts
    JOIN users ON accounts.user_id = users.id
WHERE
    account_number = $1
`

type GetAccountByAccountNumberRow struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	AccountNumber     string             `json:"account_number"`
	Currency          string             `json:"currency"`
	Balance           int64              `json:"balance"`
	Status            AccountStatus      `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ID_2              pgtype.UUID        `json:"id_2"`
	Email             string             `json:"email"`
	PasswordHash      string             `json:"password_hash"`
	FullName          string             `json:"full_name"`
	IsVerified        bool               `json:"is_verified"`
	RefreshToken      pgtype.Text        `json:"refresh_token"`
	VerificationToken pgtype.Text        `json:"verification_token"`
	CreatedAt_2       pgtype.Timestamptz `json:"created_at_2"`
	UpdatedAt_2       pgtype.Timestamptz `json:"updated_at_2"`
}

func (q *Queries) GetAccountByAccountNumber(ctx context.Context, accountNumber string) (GetAccountByAccountNumberRow, error) {
	row := q.db.QueryRow(ctx, getAccountByAccountNumber, accountNumber)
	var i GetAccountByAccountNumberRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountNumber,
		&i.Currency,
		&i.Balance,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID_2,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsVerified,
		&i.RefreshToken,
		&i.VerificationToken,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT
    id, user_id, account_number, currency, balance, status, created_at, updated_at
FROM
    accounts
WHERE
    id = $1 FOR
UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountNumber,
		&i.Currency,
		&i.Balance,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAccount = `-- name: GetUserAccount :one
SELECT
    accounts.id, user_id, account_number, currency, balance, status, accounts.created_at, accounts.updated_at, users.id, email, password_hash, full_name, is_verified, refresh_token, verification_token, users.created_at, users.updated_at
FROM
    accounts
    JOIN users ON accounts.user_id = users.id
WHERE
    user_id = $1
`

type GetUserAccountRow struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	AccountNumber     string             `json:"account_number"`
	Currency          string             `json:"currency"`
	Balance           int64              `json:"balance"`
	Status            AccountStatus      `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ID_2              pgtype.UUID        `json:"id_2"`
	Email             string             `json:"email"`
	PasswordHash      string             `json:"password_hash"`
	FullName          string             `json:"full_name"`
	IsVerified        bool               `json:"is_verified"`
	RefreshToken      pgtype.Text        `json:"refresh_token"`
	VerificationToken pgtype.Text        `json:"verification_token"`
	CreatedAt_2       pgtype.Timestamptz `json:"created_at_2"`
	UpdatedAt_2       pgtype.Timestamptz `json:"updated_at_2"`
}

func (q *Queries) GetUserAccount(ctx context.Context, userID pgtype.UUID) (GetUserAccountRow, error) {
	row := q.db.QueryRow(ctx, getUserAccount, userID)
	var i GetUserAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountNumber,
		&i.Currency,
		&i.Balance,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID_2,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsVerified,
		&i.RefreshToken,
		&i.VerificationToken,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
	)
	return i, err
}

const subtractBalance = `-- name: SubtractBalance :exec
UPDATE accounts
SET
    balance = balance - $1
WHERE
    id = $2
`

type SubtractBalanceParams struct {
	Balance int64       `json:"balance"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) SubtractBalance(ctx context.Context, arg SubtractBalanceParams) error {
	_, err := q.db.Exec(ctx, subtractBalance, arg.Balance, arg.ID)
	return err
}
