// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO
    entries (account_id, transfer_id, amount, entry_type)
VALUES
    ($1, $2, $3, $4)
RETURNING
    id, account_id, transfer_id, amount, entry_type, created_at
`

type CreateEntryParams struct {
	AccountID  pgtype.UUID   `json:"account_id"`
	TransferID pgtype.UUID   `json:"transfer_id"`
	Amount     int64         `json:"amount"`
	EntryType  EntryTypeEnum `json:"entry_type"`
}

// db/queries/entries.sql
func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.AccountID,
		arg.TransferID,
		arg.Amount,
		arg.EntryType,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransferID,
		&i.Amount,
		&i.EntryType,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountIdCreditEntry = `-- name: GetAccountIdCreditEntry :one
SELECT
    id, account_id, transfer_id, amount, entry_type, created_at
FROM
    entries
WHERE
    account_id = $1
    AND entry_type = 'CREDIT'
`

func (q *Queries) GetAccountIdCreditEntry(ctx context.Context, accountID pgtype.UUID) (Entry, error) {
	row := q.db.QueryRow(ctx, getAccountIdCreditEntry, accountID)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransferID,
		&i.Amount,
		&i.EntryType,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountIdDEBITEntry = `-- name: GetAccountIdDEBITEntry :one
SELECT
    id, account_id, transfer_id, amount, entry_type, created_at
FROM
    entries
WHERE
    account_id = $1
    AND entry_type = 'DEBIT'
`

func (q *Queries) GetAccountIdDEBITEntry(ctx context.Context, accountID pgtype.UUID) (Entry, error) {
	row := q.db.QueryRow(ctx, getAccountIdDEBITEntry, accountID)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransferID,
		&i.Amount,
		&i.EntryType,
		&i.CreatedAt,
	)
	return i, err
}

const getEntriesByAccountID = `-- name: GetEntriesByAccountID :many
SELECT
    id, account_id, transfer_id, amount, entry_type, created_at
FROM
    entries
WHERE
    account_id = $1
`

func (q *Queries) GetEntriesByAccountID(ctx context.Context, accountID pgtype.UUID) ([]Entry, error) {
	rows, err := q.db.Query(ctx, getEntriesByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TransferID,
			&i.Amount,
			&i.EntryType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
