// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkIfIdempotencyKeyExists = `-- name: CheckIfIdempotencyKeyExists :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            idempotency_keys
        WHERE
            idempotency_key = $1
    )
`

func (q *Queries) CheckIfIdempotencyKeyExists(ctx context.Context, idempotencyKey string) (bool, error) {
	row := q.db.QueryRow(ctx, checkIfIdempotencyKeyExists, idempotencyKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :one
UPDATE idempotency_keys
SET
    status_code = $2,
    response_body = $3,
    completed_at = now()
WHERE
    idempotency_key = $1
RETURNING
    idempotency_key, user_id, request_hash, status_code, response_body, locked_at, completed_at, created_at, expires_at
`

type CompleteIdempotencyKeyParams struct {
	IdempotencyKey string      `json:"idempotency_key"`
	StatusCode     pgtype.Int4 `json:"status_code"`
	ResponseBody   []byte      `json:"response_body"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, completeIdempotencyKey, arg.IdempotencyKey, arg.StatusCode, arg.ResponseBody)
	var i IdempotencyKey
	err := row.Scan(
		&i.IdempotencyKey,
		&i.UserID,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.LockedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO
    idempotency_keys (idempotency_key, user_id, request_hash, locked_at)
VALUES
    ($1, $2, $3, now()) ON CONFLICT (idempotency_key)
DO NOTHING
RETURNING
    idempotency_key, user_id, request_hash, status_code, response_body, locked_at, completed_at, created_at, expires_at
`

type CreateIdempotencyKeyParams struct {
	IdempotencyKey string      `json:"idempotency_key"`
	UserID         pgtype.UUID `json:"user_id"`
	RequestHash    string      `json:"request_hash"`
}

// db/queries/idempotency.sql
func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey, arg.IdempotencyKey, arg.UserID, arg.RequestHash)
	var i IdempotencyKey
	err := row.Scan(
		&i.IdempotencyKey,
		&i.UserID,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.LockedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT
    idempotency_key, user_id, request_hash, status_code, response_body, locked_at, completed_at, created_at, expires_at
FROM
    idempotency_keys
WHERE
    idempotency_key = $1
    AND user_id = $2
`

type GetIdempotencyKeyParams struct {
	IdempotencyKey string      `json:"idempotency_key"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.IdempotencyKey, arg.UserID)
	var i IdempotencyKey
	err := row.Scan(
		&i.IdempotencyKey,
		&i.UserID,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.LockedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
