// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (title, url, user_id) VALUES ($1, $2, $3) RETURNING id, user_id, url, title, created_at
`

type CreateLinkParams struct {
	Title  string `json:"title"`
	Url    string `json:"url"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.Title, arg.Url, arg.UserID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const getLink = `-- name: GetLink :one

SELECT id, user_id, url, title, created_at FROM links WHERE id = $1
`

// db/queries/links.sql
func (q *Queries) GetLink(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRow(ctx, getLink, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const getLinks = `-- name: GetLinks :many
SELECT id, user_id, url, title, created_at FROM links ORDER BY created_at
`

func (q *Queries) GetLinks(ctx context.Context) ([]Link, error) {
	rows, err := q.db.Query(ctx, getLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinksWithUserDetails = `-- name: GetLinksWithUserDetails :many
SELECT l.id,
    l.title,
    l.url,
    l.created_at,
    u.id AS user_id,
    u.email AS user_email
FROM links l
INNER JOIN users u ON l.user_id=u.id
`

type GetLinksWithUserDetailsRow struct {
	ID        int64              `json:"id"`
	Title     string             `json:"title"`
	Url       string             `json:"url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserID    int64              `json:"user_id"`
	UserEmail string             `json:"user_email"`
}

func (q *Queries) GetLinksWithUserDetails(ctx context.Context) ([]GetLinksWithUserDetailsRow, error) {
	rows, err := q.db.Query(ctx, getLinksWithUserDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLinksWithUserDetailsRow{}
	for rows.Next() {
		var i GetLinksWithUserDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.CreatedAt,
			&i.UserID,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMostVisitedLinks = `-- name: GetMostVisitedLinks :many
SELECT l.id, l.user_id, l.url, l.title, l.created_at, COUNT(v.id) AS visit_count
FROM links l
JOIN link_visits v ON v.link_id = l.id
GROUP BY l.id
ORDER BY visit_count DESC
LIMIT 10
`

type GetMostVisitedLinksRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Url        string             `json:"url"`
	Title      string             `json:"title"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	VisitCount int64              `json:"visit_count"`
}

func (q *Queries) GetMostVisitedLinks(ctx context.Context) ([]GetMostVisitedLinksRow, error) {
	rows, err := q.db.Query(ctx, getMostVisitedLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMostVisitedLinksRow{}
	for rows.Next() {
		var i GetMostVisitedLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.CreatedAt,
			&i.VisitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksWithTags = `-- name: ListLinksWithTags :many
SELECT l.id, l.user_id, l.url, l.title, l.created_at, ARRAY_AGG(t.name) AS tags
FROM links l
LEFT JOIN link_tags lt ON lt.link_id = l.id
LEFT JOIN tags t ON t.id = lt.tag_id
WHERE l.user_id = $1
GROUP BY l.id
`

type ListLinksWithTagsRow struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Url       string             `json:"url"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Tags      interface{}        `json:"tags"`
}

func (q *Queries) ListLinksWithTags(ctx context.Context, userID int64) ([]ListLinksWithTagsRow, error) {
	rows, err := q.db.Query(ctx, listLinksWithTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinksWithTagsRow{}
	for rows.Next() {
		var i ListLinksWithTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.CreatedAt,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
