// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Url       string             `json:"url"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type LinkTag struct {
	LinkID int64 `json:"link_id"`
	TagID  int64 `json:"tag_id"`
}

type LinkVisit struct {
	ID        int64              `json:"id"`
	LinkID    int64              `json:"link_id"`
	VisitedAt pgtype.Timestamptz `json:"visited_at"`
}

type Tag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID        int64              `json:"id"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
