// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO
    notifications (
        user_id,
        type,
        title,
        message
    )
VALUES
    ($1, $2, $3, $4)
RETURNING
    id, user_id, type, title, message, data, is_read, read_at, created_at, expires_at
`

type CreateNotificationParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Type    string      `json:"type"`
	Title   string      `json:"title"`
	Message string      `json:"message"`
}

// db/queries/notification.sql
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Message,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.Data,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserNotifications = `-- name: GetUserNotifications :many
SELECT
    id, user_id, type, title, message, data, is_read, read_at, created_at, expires_at
FROM
    notifications
WHERE
    user_id = $1
ORDER BY
    created_at DESC
`

func (q *Queries) GetUserNotifications(ctx context.Context, userID pgtype.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getUserNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Data,
			&i.IsRead,
			&i.ReadAt,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :one
UPDATE notifications
SET
    is_read = TRUE,
    read_at = now()
WHERE
    id = $1
    AND user_id = $2
RETURNING
    id, user_id, type, title, message, data, is_read, read_at, created_at, expires_at
`

type MarkNotificationAsReadParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.Data,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
