// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payroll.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkBatchCompleted = `-- name: CheckBatchCompleted :one
SELECT
    COUNT(*) AS TOTAL,
    COUNT(*) FILTER (
        WHERE
            status = 'COMPLETED'
    ) AS completed,
    COUNT(*) FILTER (
        WHERE
            status = 'FAILED'
    ) AS failed
FROM
    payroll
WHERE
    batch_id = $1
`

type CheckBatchCompletedRow struct {
	Total     int64 `json:"total"`
	Completed int64 `json:"completed"`
	Failed    int64 `json:"failed"`
}

func (q *Queries) CheckBatchCompleted(ctx context.Context, batchID pgtype.UUID) (CheckBatchCompletedRow, error) {
	row := q.db.QueryRow(ctx, checkBatchCompleted, batchID)
	var i CheckBatchCompletedRow
	err := row.Scan(&i.Total, &i.Completed, &i.Failed)
	return i, err
}

const createPayroll = `-- name: CreatePayroll :one
INSERT INTO
    payroll (batch_id, employee_account_id, amount, status)
VALUES
    ($1, $2, $3, $4)
RETURNING
    id, batch_id, employee_account_id, amount, status, created_at
`

type CreatePayrollParams struct {
	BatchID           pgtype.UUID       `json:"batch_id"`
	EmployeeAccountID pgtype.UUID       `json:"employee_account_id"`
	Amount            int64             `json:"amount"`
	Status            PayrollItemStatus `json:"status"`
}

func (q *Queries) CreatePayroll(ctx context.Context, arg CreatePayrollParams) (Payroll, error) {
	row := q.db.QueryRow(ctx, createPayroll,
		arg.BatchID,
		arg.EmployeeAccountID,
		arg.Amount,
		arg.Status,
	)
	var i Payroll
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.EmployeeAccountID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createPayrollBatch = `-- name: CreatePayrollBatch :one
INSERT INTO
    payroll_batches (company_account_id, schedule_date, status)
VALUES
    ($1, $2, $3)
RETURNING
    id, company_account_id, schedule_date, status, payment_interval, created_at, updated_at
`

type CreatePayrollBatchParams struct {
	CompanyAccountID pgtype.UUID        `json:"company_account_id"`
	ScheduleDate     pgtype.Timestamptz `json:"schedule_date"`
	Status           PayrollBatchStatus `json:"status"`
}

// db/queries/payroll.sql
func (q *Queries) CreatePayrollBatch(ctx context.Context, arg CreatePayrollBatchParams) (PayrollBatch, error) {
	row := q.db.QueryRow(ctx, createPayrollBatch, arg.CompanyAccountID, arg.ScheduleDate, arg.Status)
	var i PayrollBatch
	err := row.Scan(
		&i.ID,
		&i.CompanyAccountID,
		&i.ScheduleDate,
		&i.Status,
		&i.PaymentInterval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finalizeBatch = `-- name: FinalizeBatch :one
UPDATE payroll_batches
SET
    status = $2,
    schedule_date = $3,
    updated_at = now()
WHERE
    id = $1
RETURNING
    id, company_account_id, schedule_date, status, payment_interval, created_at, updated_at
`

type FinalizeBatchParams struct {
	ID           pgtype.UUID        `json:"id"`
	Status       PayrollBatchStatus `json:"status"`
	ScheduleDate pgtype.Timestamptz `json:"schedule_date"`
}

func (q *Queries) FinalizeBatch(ctx context.Context, arg FinalizeBatchParams) (PayrollBatch, error) {
	row := q.db.QueryRow(ctx, finalizeBatch, arg.ID, arg.Status, arg.ScheduleDate)
	var i PayrollBatch
	err := row.Scan(
		&i.ID,
		&i.CompanyAccountID,
		&i.ScheduleDate,
		&i.Status,
		&i.PaymentInterval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBatchById = `-- name: GetBatchById :one
SELECT
    id, company_account_id, schedule_date, status, payment_interval, created_at, updated_at
FROM
    payroll_batches
WHERE
    id = $1
`

func (q *Queries) GetBatchById(ctx context.Context, id pgtype.UUID) (PayrollBatch, error) {
	row := q.db.QueryRow(ctx, getBatchById, id)
	var i PayrollBatch
	err := row.Scan(
		&i.ID,
		&i.CompanyAccountID,
		&i.ScheduleDate,
		&i.Status,
		&i.PaymentInterval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBatchForUpdate = `-- name: GetBatchForUpdate :one
SELECT
    id, company_account_id, schedule_date, status, payment_interval, created_at, updated_at
FROM
    payroll_batches
WHERE
    id = $1 FOR
UPDATE
`

func (q *Queries) GetBatchForUpdate(ctx context.Context, id pgtype.UUID) (PayrollBatch, error) {
	row := q.db.QueryRow(ctx, getBatchForUpdate, id)
	var i PayrollBatch
	err := row.Scan(
		&i.ID,
		&i.CompanyAccountID,
		&i.ScheduleDate,
		&i.Status,
		&i.PaymentInterval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDuePayrollBatches = `-- name: GetDuePayrollBatches :many
SELECT
    id, company_account_id, schedule_date, status, payment_interval, created_at, updated_at
FROM
    payroll_batches
WHERE
    schedule_date <= now()
    AND status = 'PENDING' FOR
UPDATE SKIP LOCKED
`

func (q *Queries) GetDuePayrollBatches(ctx context.Context) ([]PayrollBatch, error) {
	rows, err := q.db.Query(ctx, getDuePayrollBatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PayrollBatch{}
	for rows.Next() {
		var i PayrollBatch
		if err := rows.Scan(
			&i.ID,
			&i.CompanyAccountID,
			&i.ScheduleDate,
			&i.Status,
			&i.PaymentInterval,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPayrollBatchById = `-- name: GetPayrollBatchById :one
SELECT
    id, company_account_id, schedule_date, status, payment_interval, created_at, updated_at
FROM
    payroll_batches
WHERE
    id = $1
    AND company_account_id = $2
`

type GetPayrollBatchByIdParams struct {
	ID               pgtype.UUID `json:"id"`
	CompanyAccountID pgtype.UUID `json:"company_account_id"`
}

func (q *Queries) GetPayrollBatchById(ctx context.Context, arg GetPayrollBatchByIdParams) (PayrollBatch, error) {
	row := q.db.QueryRow(ctx, getPayrollBatchById, arg.ID, arg.CompanyAccountID)
	var i PayrollBatch
	err := row.Scan(
		&i.ID,
		&i.CompanyAccountID,
		&i.ScheduleDate,
		&i.Status,
		&i.PaymentInterval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayrollItemByID = `-- name: GetPayrollItemByID :one
SELECT
    payroll.id, payroll.batch_id, payroll.employee_account_id, payroll.amount, payroll.status, payroll.created_at,
    payroll_batches.id, payroll_batches.company_account_id, payroll_batches.schedule_date, payroll_batches.status, payroll_batches.payment_interval, payroll_batches.created_at, payroll_batches.updated_at,
    accounts.id, accounts.user_id, accounts.account_number, accounts.currency, accounts.balance, accounts.status, accounts.created_at, accounts.updated_at
FROM
    payroll
    JOIN payroll_batches ON payroll_batches.id = payroll.batch_id
    JOIN accounts ON accounts.id = payroll_batches.company_account_id
WHERE
    payroll.id = $1
`

type GetPayrollItemByIDRow struct {
	ID                pgtype.UUID            `json:"id"`
	BatchID           pgtype.UUID            `json:"batch_id"`
	EmployeeAccountID pgtype.UUID            `json:"employee_account_id"`
	Amount            int64                  `json:"amount"`
	Status            PayrollItemStatus      `json:"status"`
	CreatedAt         pgtype.Timestamptz     `json:"created_at"`
	ID_2              pgtype.UUID            `json:"id_2"`
	CompanyAccountID  pgtype.UUID            `json:"company_account_id"`
	ScheduleDate      pgtype.Timestamptz     `json:"schedule_date"`
	Status_2          PayrollBatchStatus     `json:"status_2"`
	PaymentInterval   PayrollPaymentInterval `json:"payment_interval"`
	CreatedAt_2       pgtype.Timestamptz     `json:"created_at_2"`
	UpdatedAt         pgtype.Timestamptz     `json:"updated_at"`
	ID_3              pgtype.UUID            `json:"id_3"`
	UserID            pgtype.UUID            `json:"user_id"`
	AccountNumber     string                 `json:"account_number"`
	Currency          string                 `json:"currency"`
	Balance           int64                  `json:"balance"`
	Status_3          AccountStatus          `json:"status_3"`
	CreatedAt_3       pgtype.Timestamptz     `json:"created_at_3"`
	UpdatedAt_2       pgtype.Timestamptz     `json:"updated_at_2"`
}

func (q *Queries) GetPayrollItemByID(ctx context.Context, id pgtype.UUID) (GetPayrollItemByIDRow, error) {
	row := q.db.QueryRow(ctx, getPayrollItemByID, id)
	var i GetPayrollItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.EmployeeAccountID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.ID_2,
		&i.CompanyAccountID,
		&i.ScheduleDate,
		&i.Status_2,
		&i.PaymentInterval,
		&i.CreatedAt_2,
		&i.UpdatedAt,
		&i.ID_3,
		&i.UserID,
		&i.AccountNumber,
		&i.Currency,
		&i.Balance,
		&i.Status_3,
		&i.CreatedAt_3,
		&i.UpdatedAt_2,
	)
	return i, err
}

const getPendingBatchPayrollItem = `-- name: GetPendingBatchPayrollItem :many
SELECT
    id, batch_id, employee_account_id, amount, status, created_at
FROM
    payroll
WHERE
    batch_id = $1
    AND status = 'PENDING'
`

func (q *Queries) GetPendingBatchPayrollItem(ctx context.Context, batchID pgtype.UUID) ([]Payroll, error) {
	rows, err := q.db.Query(ctx, getPendingBatchPayrollItem, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payroll{}
	for rows.Next() {
		var i Payroll
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.EmployeeAccountID,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBatchToProcessing = `-- name: UpdateBatchToProcessing :one
UPDATE payroll_batches
SET
    status = 'PROCESSING'
WHERE
    id = $1
RETURNING
    id, company_account_id, schedule_date, status, payment_interval, created_at, updated_at
`

func (q *Queries) UpdateBatchToProcessing(ctx context.Context, id pgtype.UUID) (PayrollBatch, error) {
	row := q.db.QueryRow(ctx, updateBatchToProcessing, id)
	var i PayrollBatch
	err := row.Scan(
		&i.ID,
		&i.CompanyAccountID,
		&i.ScheduleDate,
		&i.Status,
		&i.PaymentInterval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePayrollToCompleted = `-- name: UpdatePayrollToCompleted :one
UPDATE payroll
SET
    status = 'COMPLETED'
WHERE
    id = $1
RETURNING
    id, batch_id, employee_account_id, amount, status, created_at
`

func (q *Queries) UpdatePayrollToCompleted(ctx context.Context, id pgtype.UUID) (Payroll, error) {
	row := q.db.QueryRow(ctx, updatePayrollToCompleted, id)
	var i Payroll
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.EmployeeAccountID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updatePayrollToFailed = `-- name: UpdatePayrollToFailed :one
UPDATE payroll
SET
    status = 'FAILED'
WHERE
    id = $1
RETURNING
    id, batch_id, employee_account_id, amount, status, created_at
`

func (q *Queries) UpdatePayrollToFailed(ctx context.Context, id pgtype.UUID) (Payroll, error) {
	row := q.db.QueryRow(ctx, updatePayrollToFailed, id)
	var i Payroll
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.EmployeeAccountID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
