// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateAccount(ctx context.Context, id pgtype.UUID) error
	AddBalance(ctx context.Context, arg AddBalanceParams) error
	CheckIfAccountNumberExists(ctx context.Context, accountNumber string) (bool, error)
	CheckIfIdempotencyKeyExists(ctx context.Context, idempotencyKey string) (bool, error)
	CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (IdempotencyKey, error)
	// db/queries/idempotency.sql
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error)
	// db/queries/transfers.sql
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// db/queries/accounts.sql
	CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (Account, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	EmailExists(ctx context.Context, email string) (bool, error)
	GetAccount(ctx context.Context, id pgtype.UUID) (Account, error)
	GetAccountByAccountNumber(ctx context.Context, accountNumber string) (GetAccountByAccountNumberRow, error)
	GetAccountForUpdate(ctx context.Context, id pgtype.UUID) (Account, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	GetIncomingTransfers(ctx context.Context, arg GetIncomingTransfersParams) ([]Transfer, error)
	GetOutgoingTransfers(ctx context.Context, arg GetOutgoingTransfersParams) ([]Transfer, error)
	GetTransferById(ctx context.Context, id pgtype.UUID) (Transfer, error)
	// db/queries/users.sql
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserAccount(ctx context.Context, userID pgtype.UUID) (GetUserAccountRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (User, error)
	InsertVerificationToken(ctx context.Context, arg InsertVerificationTokenParams) (User, error)
	ListUsers(ctx context.Context) ([]User, error)
	SubtractBalance(ctx context.Context, arg SubtractBalanceParams) error
	UpdateTransferStatus(ctx context.Context, arg UpdateTransferStatusParams) error
	VerifyUser(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
