// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	CreateTag(ctx context.Context, name string) (Tag, error)
	CreateUser(ctx context.Context, email string) (User, error)
	DeleteUser(ctx context.Context, id int64) error
	// db/queries/links.sql
	GetLink(ctx context.Context, id int64) (Link, error)
	GetLinks(ctx context.Context) ([]Link, error)
	GetLinksWithUserDetails(ctx context.Context) ([]GetLinksWithUserDetailsRow, error)
	GetMostVisitedLinks(ctx context.Context) ([]GetMostVisitedLinksRow, error)
	// db/migrations/tags.sql
	GetTag(ctx context.Context, id int64) (Tag, error)
	GetTags(ctx context.Context) ([]Tag, error)
	// db/queries/users.sql
	GetUser(ctx context.Context, id int64) (User, error)
	ListLinksWithTags(ctx context.Context, userID int64) ([]ListLinksWithTagsRow, error)
	ListUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
