// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO
    transfers (
        from_account_id,
        to_account_id,
        amount,
        description,
        status
    )
VALUES
    ($1, $2, $3, $4, $5)
RETURNING
    id, from_account_id, to_account_id, amount, status, reference, description, created_at
`

type CreateTransferParams struct {
	FromAccountID pgtype.UUID `json:"from_account_id"`
	ToAccountID   pgtype.UUID `json:"to_account_id"`
	Amount        int64       `json:"amount"`
	Description   pgtype.Text `json:"description"`
	Status        string      `json:"status"`
}

// db/queries/transfers.sql
func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.Amount,
		arg.Description,
		arg.Status,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.Status,
		&i.Reference,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getIncomingTransfers = `-- name: GetIncomingTransfers :many
SELECT
    id, from_account_id, to_account_id, amount, status, reference, description, created_at
FROM
    transfers
WHERE
    to_account_id = $1
ORDER BY
    created_at DESC
LIMIT
    $2
OFFSET
    $3
`

type GetIncomingTransfersParams struct {
	ToAccountID pgtype.UUID `json:"to_account_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) GetIncomingTransfers(ctx context.Context, arg GetIncomingTransfersParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, getIncomingTransfers, arg.ToAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.Amount,
			&i.Status,
			&i.Reference,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutgoingTransfers = `-- name: GetOutgoingTransfers :many
SELECT
    id, from_account_id, to_account_id, amount, status, reference, description, created_at
FROM
    transfers
WHERE
    from_account_id = $1
ORDER BY
    created_at DESC
LIMIT
    $2
OFFSET
    $3
`

type GetOutgoingTransfersParams struct {
	FromAccountID pgtype.UUID `json:"from_account_id"`
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
}

func (q *Queries) GetOutgoingTransfers(ctx context.Context, arg GetOutgoingTransfersParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, getOutgoingTransfers, arg.FromAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.Amount,
			&i.Status,
			&i.Reference,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransferById = `-- name: GetTransferById :one
SELECT
    id, from_account_id, to_account_id, amount, status, reference, description, created_at
FROM
    transfers
WHERE
    id = $1
`

func (q *Queries) GetTransferById(ctx context.Context, id pgtype.UUID) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransferById, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.Status,
		&i.Reference,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const updateTransferStatus = `-- name: UpdateTransferStatus :exec
UPDATE transfers
SET
    status = $1
WHERE
    id = $2
`

type UpdateTransferStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTransferStatus(ctx context.Context, arg UpdateTransferStatusParams) error {
	_, err := q.db.Exec(ctx, updateTransferStatus, arg.Status, arg.ID)
	return err
}
