// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (email, password_hash, full_name)
VALUES
    ($1, $2, $3)
RETURNING
    id, email, password_hash, full_name, is_verified, refresh_token, verification_token, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	FullName     string `json:"full_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.FullName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsVerified,
		&i.RefreshToken,
		&i.VerificationToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE
    id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const emailExists = `-- name: EmailExists :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            users
        WHERE
            email = $1
    )
`

func (q *Queries) EmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUser = `-- name: GetUser :one
SELECT
    id, email, password_hash, full_name, is_verified, refresh_token, verification_token, created_at, updated_at
FROM
    users
WHERE
    id = $1
`

// db/queries/users.sql
func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsVerified,
		&i.RefreshToken,
		&i.VerificationToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id, email, password_hash, full_name, is_verified, refresh_token, verification_token, created_at, updated_at
FROM
    users
WHERE
    email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsVerified,
		&i.RefreshToken,
		&i.VerificationToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
UPDATE users
SET
    refresh_token = $1
WHERE
    id = $2
RETURNING
    id, email, password_hash, full_name, is_verified, refresh_token, verification_token, created_at, updated_at
`

type InsertRefreshTokenParams struct {
	RefreshToken pgtype.Text `json:"refresh_token"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (User, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken, arg.RefreshToken, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsVerified,
		&i.RefreshToken,
		&i.VerificationToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertVerificationToken = `-- name: InsertVerificationToken :one
UPDATE users
SET
    verification_token = $1
WHERE
    id = $2
RETURNING
    id, email, password_hash, full_name, is_verified, refresh_token, verification_token, created_at, updated_at
`

type InsertVerificationTokenParams struct {
	VerificationToken pgtype.Text `json:"verification_token"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) InsertVerificationToken(ctx context.Context, arg InsertVerificationTokenParams) (User, error) {
	row := q.db.QueryRow(ctx, insertVerificationToken, arg.VerificationToken, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsVerified,
		&i.RefreshToken,
		&i.VerificationToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    id, email, password_hash, full_name, is_verified, refresh_token, verification_token, created_at, updated_at
FROM
    users
ORDER BY
    id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.IsVerified,
			&i.RefreshToken,
			&i.VerificationToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const verifyUser = `-- name: VerifyUser :exec
UPDATE users
SET
    is_verified = TRUE
WHERE
    id = $1
`

func (q *Queries) VerifyUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, verifyUser, id)
	return err
}
